/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class TakeoffEngine {
  constructor(transform: Transform, scale?: Scale | undefined | null)
  get state(): TakeoffState
  set state(state: TakeoffState)
  get transform(): Transform
  set transform(transform: Transform)
  get scale(): Scale | null
  set scale(scale: Scale | null)
  addTransformCallback(callback: ((err: Error | null, arg: Transform) => any)): void
  /** Transform a point from screen coordinates to world coordinates */
  screenToWorld(point: Point): Point
  /** Transform a point from world coordinates to screen coordinates */
  worldToScreen(point: Point): Point
  /** Apply zoom transformation around a specific point */
  zoomAroundPoint(center: Point, zoomFactor: number): Transform
  /** Apply pan transformation */
  pan(deltaX: number, deltaY: number): Transform
  /** Reset transform to identity */
  resetTransform(): Transform
  /** Fit image to viewport */
  fitToViewport(imageWidth: number, imageHeight: number, viewportWidth: number, viewportHeight: number): Transform
}

export declare function plus100(input: number): number

export declare function sum(a: number, b: number): number
/** Represents a line segment between two points */
export interface Line {
  start: Point
  end: Point
}

/** Types of measurements that can be created */
export type Measurement =
  | { type: 'Linear', id: string, line?: Line, polyline?: Polyline, scale: Scale, displayUnit: Unit }
  | { type: 'Area', id: string, rectangle?: Rectangle, polygon?: Polygon, scale: Scale, displayUnit: Unit }
  | { type: 'Count', id: string, point: Point }

/** Represents a 2D point with floating point coordinates */
export interface Point {
  x: number
  y: number
}

/** Represents a polygon defined by a list of points */
export interface Polygon {
  points: Array<Point>
}

export interface Polyline {
  points: Array<Point>
}

/** Represents a rectangle defined by two points */
export interface Rectangle {
  start: Point
  end: Point
}

/** Scale information for converting pixel measurements to real-world measurements */
export interface Scale {
  /** Pixel distance */
  pixelDistance: number
  /** Real-world distance */
  realDistance: number
  /** Unit for the real-world distance */
  unit: Unit
}

/** State management for takeoff measurements */
export interface TakeoffState {
  measurements: Array<Measurement>
  scale?: Scale
  transform: Transform
  count: number
  /** File ID for PDF files (null for images) */
  fileId?: string
  /** Page number for PDF files (null for images) */
  pageNumber?: number
}

/** Coordinate transformation for zoom and pan */
export interface Transform {
  scale: number
  offsetX: number
  offsetY: number
}

/** Measurement units supported by the system */
export declare const enum Unit {
  /** Imperial units */
  Yards = 'Yards',
  Feet = 'Feet',
  Inches = 'Inches',
  /** Metric units */
  Meters = 'Meters',
  Centimeters = 'Centimeters'
}
